### ISSUE TITLE
top notif badge was uncentered

### ISSUE THREAD

**Issue by dredshep** [VILPAUTOEE/Lemmy_css#1]
This kinda centers it:

![image](https://github.com/VILPAUTOEE/Lemmy_css/assets/78047001/b56a0095-0ab3-47f4-8c9c-8fdde098a8ab)

```css
.nav-link .badge.badge-light {
  background-color: #ff4500;
  color: white;
  aspect-ratio: 1/1;
  width: 2ch;
  height: 2ch;
  padding-bottom: 14px;
  padding-right: 10px;
}
```
